# Generated by Django 5.0.7 on 2024-08-01 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.BigAutoField(primary_key=True, serialize=False)),
                ('name_usuario', models.TextField(max_length=255)),
                ('age_usuario', models.IntegerField()),
            ],
        ),
    ]
